CREATE DEFINER=`TA`@`%` PROCEDURE `LoadDataForChartHistory`(IN DateTimeFrom DATETIME,
IN DateTimeTo DATETIME)
BEGIN
	SELECT
        SUM(CASE WHEN Judge_VP = 'OK' THEN 1 ELSE 0 END) as VPOK,
        SUM(CASE WHEN Judge_GAS = 'OK' THEN 1 ELSE 0 END) as GASOILOK,
        SUM(CASE WHEN Judge_WI1WITH = 'OK' THEN 1 ELSE 0 END) as WI1WITHOK,
        SUM(CASE WHEN Judge_WI1START = 'OK' THEN 1 ELSE 0 END) as WI1STARTOK,
        SUM(CASE WHEN Judge_IP = 'OK' THEN 1 ELSE 0 END) as IPOK,
        SUM(CASE WHEN Judge_DF = 'OK' THEN 1 ELSE 0 END) as DFOK,
        SUM(CASE WHEN Judge_TEMP = 'OK' THEN 1 ELSE 0 END) as TEMPOK,
        SUM(CASE WHEN Judge_IOT = 'OK' THEN 1 ELSE 0 END) as IOTOK,
        SUM(CASE WHEN Judge_WI2 = 'OK' THEN 1 ELSE 0 END) as WI2OK,
        SUM(CASE WHEN Judge_PAN = 'OK' THEN 1 ELSE 0 END) as PANOK,
        SUM(CASE WHEN Judge_CAMBACK = 'OK' THEN 1 ELSE 0 END) as CAMBACKOK,
        SUM(CASE WHEN Judge_CAMFRONT = 'OK' THEN 1 ELSE 0 END) as CAMFRONTOK,

        SUM(CASE WHEN Judge_VP = 'NG' THEN 1 ELSE 0 END) as VPNG,
        SUM(CASE WHEN Judge_GAS = 'NG' THEN 1 ELSE 0 END) as GASOILNG,
        SUM(CASE WHEN Judge_WI1WITH = 'NG' THEN 1 ELSE 0 END) as WI1WITHNG,
        SUM(CASE WHEN Judge_WI1START = 'NG' THEN 1 ELSE 0 END) as WI1STARTNG,
        SUM(CASE WHEN Judge_IP = 'NG' THEN 1 ELSE 0 END) as IPNG,
        SUM(CASE WHEN Judge_DF = 'NG' THEN 1 ELSE 0 END) as DFNG,
        SUM(CASE WHEN Judge_TEMP = 'NG' THEN 1 ELSE 0 END) as TEMPNG,
        SUM(CASE WHEN Judge_IOT = 'NG' THEN 1 ELSE 0 END) as IOTNG,
        SUM(CASE WHEN Judge_WI2 = 'NG' THEN 1 ELSE 0 END) as WI2NG,
        SUM(CASE WHEN Judge_PAN = 'NG' THEN 1 ELSE 0 END) as PANNG,
        SUM(CASE WHEN Judge_CAMBACK = 'NG' THEN 1 ELSE 0 END) as CAMBACKNG,
        SUM(CASE WHEN Judge_CAMFRONT = 'NG' THEN 1 ELSE 0 END) as CAMFRONTNG,

        SUM(CASE WHEN Judge_VP = 'PD' THEN 1 ELSE 0 END) as VPPENDING,
        SUM(CASE WHEN Judge_GAS = 'PD' THEN 1 ELSE 0 END) as GASOILPENDING,
        SUM(CASE WHEN Judge_WI1WITH = 'PD' THEN 1 ELSE 0 END) as WI1WITHPENDING,
        SUM(CASE WHEN Judge_WI1START = 'PD' THEN 1 ELSE 0 END) as WI1STARTPENDING,
        SUM(CASE WHEN Judge_IP = 'PD' THEN 1 ELSE 0 END) as IPPENDING,
        SUM(CASE WHEN Judge_DF = 'PD' THEN 1 ELSE 0 END) as DFPENDING,
        SUM(CASE WHEN Judge_TEMP = 'PD' THEN 1 ELSE 0 END) as TEMPPENDING,
        SUM(CASE WHEN Judge_IOT = 'PD' THEN 1 ELSE 0 END) as IOTPENDING,
        SUM(CASE WHEN Judge_WI2 = 'PD' THEN 1 ELSE 0 END) as WI2PENDING,
        SUM(CASE WHEN Judge_PAN = 'PD' THEN 1 ELSE 0 END) as PANPENDING,
        SUM(CASE WHEN Judge_CAMBACK = 'PD' THEN 1 ELSE 0 END) as CAMBACKPENDING,
        SUM(CASE WHEN Judge_CAMFRONT = 'PD' THEN 1 ELSE 0 END) as CAMFRONTPENDING,

        SUM(CASE WHEN Judge_Total = 'OK' THEN 1 ELSE 0 END) as TotalOK,
        SUM(CASE WHEN Judge_Total = 'NG' THEN 1 ELSE 0 END) as TotalNG
		FROM DataCheckFinal where TimeUpdate Between DateTimeFrom AND DateTimeTo;
END